# Generated by Django 5.1.6 on 2025-06-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='date_submitted',
            new_name='date_filed',
        ),
        migrations.AddField(
            model_name='complaint',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='complaint_files/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('Electricity', 'Electricity'), ('Water', 'Water'), ('Road', 'Road'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
